var very_small = {x: [1882.34, 1882.34, 3243.81, 3632.81, 1882.34],
            y: [0, 1, 1, 0, 0],
            mode: 'none',
	    opacity: 0.25, 		    
            type: 'scatter',
	    fill: 'toself',
	    name: 'Very small',
            marker: {color: 'blue'},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			};

var very_small_interval = {x: [1882.34, 3438.31],
            y: [0.5, 0.5],
            type: 'scatter',
            mode: 'lines+markers',
	    opacity: 0.35, 
            marker: {color: 'blue'},
            showlegend: false,
    	    xaxis: 'x2',
	    yaxis: 'y2',
			};

var very_small_projection_left = {x: [1882.34, 3000],
            y: [0.5, 0],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'blue'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			};

var very_small_projection_right = {x: [3438.31, 6500],
            y: [0.5, 0],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'blue'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			};

var small = {
            x: [3243.81, 3632.81, 4799.78, 5188.78, 3243.81],
            y: [0, 1, 1, 0, 0],
            mode: 'none',
	    opacity: 0.25, 
	    color: 'orange',
            type: 'scatter',
	    fill: 'toself',
	    name: 'Small',
    	    xaxis: 'x2',
	    yaxis: 'y2',
        };

var small_interval = {x: [3438.31, 4994.28],
            y: [0.5, 0.5],
            type: 'scatter',
            mode: 'lines+markers',
	    opacity: 0.35, 
            marker: {color: 'orange'},
            showlegend: false,
    	    xaxis: 'x2',
	    yaxis: 'y2',
			};

var small_projection_left = {x: [3438.31, 3000],
            y: [0.5, 0],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'orange'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			};

var small_projection_right = {x: [4994.28, 6500],
            y: [0.5, 0],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'orange'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			};

var medium = {
            x: [4799.78, 5188.78, 6355.75, 6744.75, 4799.78],
            y: [0, 1, 1, 0, 0],
            mode: 'none',
		    opacity: 0.25, 
		    color: 'yellow',
            type: 'scatter',
		    fill: 'toself',
			name: 'Medium',
    	    xaxis: 'x2',
	    yaxis: 'y2',
        };

var medium_interval = {x: [4994.28, 6550.26],
            y: [0.5, 0.5],
            type: 'scatter',
            mode: 'lines+markers',
	    opacity: 0.35, 
            marker: {color: 'red'},
            showlegend: false,
    	    xaxis: 'x2',
	    yaxis: 'y2',
			};

var medium_projection_left = {x: [4994.28, 3000],
            y: [0.5, 0],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'red'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			};

var medium_projection_right = {x: [6550.26, 6500],
            y: [0.5, 0],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'red'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			};

var large = {
            x: [6355.75, 6744.75, 7911.72, 8300.72, 6355.75],
            y: [0, 1, 1, 0, 0],
            mode: 'none',
		    opacity: 0.25, 
		    color: 'yellow',
            type: 'scatter',
		    fill: 'toself',
			name: 'Large',
    	    xaxis: 'x2',
	    yaxis: 'y2',
        };

var large_interval = {x: [6550.26, 8106.23],
            y: [0.5, 0.5],
            type: 'scatter',
            mode: 'lines+markers',
	    opacity: 0.35, 
            marker: {color: 'magenta'},
            showlegend: false,
    	    xaxis: 'x2',
	    yaxis: 'y2',
			};

var large_projection_left = {x: [6550.26, 3000],
            y: [0.5, 0],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'magenta'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			};

var large_projection_right = {x: [8106.23, 6500],
            y: [0.5, 0],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'magenta'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			};

var very_large = {
            x: [7911.72, 8300.72, 9662.20, 9662.20, 7911.72],
            y: [0, 1, 1, 0, 0],
            mode: 'none',
		    opacity: 0.25, 
		    color: 'yellow',
            type: 'scatter',
		    fill: 'toself',
			name: 'Very large',
    	    xaxis: 'x2',
	    yaxis: 'y2',
        }

var very_large_interval = {x: [8106.23, 9662.20],
            y: [0.5, 0.5],
            type: 'scatter',
            mode: 'lines+markers',
	    opacity: 0.35, 
            marker: {color: 'grey'},
            showlegend: false,
    	    xaxis: 'x2',
	    yaxis: 'y2',
			};

var very_large_projection_left = {x: [8106.23, 3000],
            y: [0.5, 0],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'grey'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			};

var very_large_projection_right = {x: [9662.20, 6500],
            y: [0.5, 0],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'grey'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			};

var table = { type: 'table',
       header: {
         values: [["<b>Partition interval</b>"], ["<b>Term</b>"], ["<b>Term interval</b>"], ["<b>Intersection</b>"], ["<b>Union</b>"], ["<b>Similarity</b>"]],
         align: "center",
         line: {width: 1, color: 'black'},
         fill: {color: "grey"},

         font: {family: "Arial", size: 12, color: "white"}
       },
       cells: {
         values: [["[3750, 6400]", "[3750, 6400]", "[3750, 6400]", "[3750, 6400]", "[3750, 6400]"], 
	          ["Very small", "Small", "<b>Medium</b>", "Large", "Very large"], 
                  ["[1882.34, 3438.31]", "[3438.31, 4994.28]", "[4994.28, 6550.26]", "[6550.26, 8106.23]", "[8106.23, 9662.20]"], 
                  ["0.00", "1244.28", "1405.72", "0.00", "0.00"],       
                  ["4517.66", "2961.69", "2800.26", "4356.23", "5912.20"], 
                  ["0", "0.420", "<b>0.502</b>", "0", "0"]],
         align: "center",
         line: {color: "black", width: 1},
         font: {family: "Arial", size: 11, color: ["black"]},
         xaxis: 'x1',
         yaxis: 'y1',
         domain: {x: [0, 0.5], y: [0.5,1]},
         //domain: {column: 0, row: 0},
       }
}


var trace1 = {
            type: 'scatter',  // all "scatter" attributes: https://plotly.com/javascript/reference/#scatter
            mode: 'lines',
            x: [1882.34, 9662.20],     // more about "x": #scatter-x
            y: [0.5, 0.5],     // #scatter-y
            marker: {         // marker is an object, valid marker keys: #scatter-marker
                color: 'rgb(16, 32, 77)' // more about "marker.color": #scatter-marker-color
            },
            showlegend: false,
	    line: {dash: "dash"},
            xaxis: 'x2',
            yaxis: 'y2',
        }
var trace2 = {
            type: 'scatter',  // all "scatter" attributes: https://plotly.com/javascript/reference/#scatter
            x: [3000, 4500, 6300, 6500, 3000],     // more about "x": #scatter-x
            y: [0, 1, 1, 0, 0],     // #scatter-y
            marker: {         // marker is an object, valid marker keys: #scatter-marker
                color: 'rgb(16, 32, 77)' // more about "marker.color": #scatter-marker-color
            },
            showlegend: false,
            xaxis: 'x2',
            yaxis: 'y2',
        }

var trace3 = {
            type: 'scatter',  // all "scatter" attributes: https://plotly.com/javascript/reference/#scatter			
            x: [3000, 3750, 6400, 6500, 3000],     // more about "x": #scatter-x
            y: [0, 0.5, 0.5, 0, 0],     // #scatter-y
            marker: {         // marker is an object, valid marker keys: #scatter-marker
                color: 'green' // more about "marker.color": #scatter-marker-color
            },
            showlegend: false,
	    fill: 'tozerox',
            xaxis: 'x2',
            yaxis: 'y2',
        }

var axis = {
    showline: false,
    zeroline: false,
    showgrid: true,
    mirror:true,
    ticklen: 4,
    gridcolor: '#ffffff',
    tickfont: {size: 12},
  }

var axis1_table = {domain: [0, 1], anchor: 'y1'}
var axis2_table = {domain: [0.5, 1], anchor: 'x1'}

var axis1 = {domain: [0, 1], range: [1882.34, 9662.20], anchor: 'y2'}
var axis2 = {domain: [0, 0.5], anchor: 'x2'}

var layout = {                     // all "layout" attributes: #layout
        title: 'Effect of alpha-cut on linguistic approximation',  // more about "layout.title": #layout-title
        //grid: {rows: 1, columns: 1, pattern: 'independent'},
	    //showlegend: false,
        height: 600,
	    legend: {
        x: 1,
	    //xanchor: 'right',
	    y: 0.1
	},
        xaxis1: Object.assign(axis1_table,axis),
        yaxis1: Object.assign(axis2_table,axis),
        xaxis2: Object.assign(axis1,axis),
        yaxis2: Object.assign(axis2,axis),
	annotations: [{
		x: 2660.325,
		y: 0.55,
		xref: 'x2',
		yref: 'y2',
		text: 'Very small',
		opacity: 0.5,
		font: {color: 'blue'},
		showarrow: false,
		//ax: 0,
		//ay: -40
        },
	{
		x: 4216.295,
		y: 0.55,
		xref: 'x2',
		yref: 'y2',
		text: 'Small',
		opacity: 0.5,
		font: {color: 'orange'},
		showarrow: false,
		//ax: 0,
		//ay: -40
        },
        {
		x: 5772.265,
		y: 0.55,
		xref: 'x2',
		yref: 'y2',
		text: 'Medium',
		opacity: 0.5,
		font: {color: 'red'},
		showarrow: false,
		//ax: 0,
		//ay: -40
        },
        {
		x: 7328.245,
		y: 0.55,
		xref: 'x2',
		yref: 'y2',
		text: 'Large',
		opacity: 0.5,
		font: {color: 'magenta'},
		showarrow: false,
		//ax: 0,
		//ay: -40
        },
        {
		x: 8884.215,
		y: 0.55,
		xref: 'x2',
		yref: 'y2',
		text: 'Very large',
		opacity: 0.5,
		font: {color: 'grey'},
		showarrow: false,
		//ax: 0,
		//ay: -40
        }],		
        sliders: [{
	      name: "alpha_cut_slider",
          pad: {t: 25},
	  active: 5,
          currentvalue: {
            xanchor: 'center',
            prefix: 'Alpha-cut: ',
	    //suffix: '\t\tColor is brown',
            font: {
              color: '#888',
              size: 20
            }
          },
		steps: [{
              label: '0.0',
              method: 'restyle',
              args: ['currentvalue.suffix', '\t\tColor is brown']
            }, {
              label: '0.1',
              method: 'restyle',
              args: ['currentvalue.suffix', '\t\tColor is brown']
            }, {
              label: '0.2',
              method: 'restyle',
              args: ['currentvalue.suffix', '\t\tColor is brown']
            }, {
              label: '0.3',
              method: 'restyle',
              args: ['currentvalue.suffix', '\t\tColor is brown']
            }, {
              label: '0.4',
              method: 'restyle',
	      args: ['currentvalue.suffix', '\t\tColor is brown']
            }, {
              label: '0.5',
              method: 'restyle',
	      args: ['currentvalue.suffix', '\t\tColor is amber']
            }, {
              label: '0.6',
              method: 'restyle',
	      args: ['currentvalue.suffix', '\t\tColor is amber']
            }, {
              label: '0.7',
              method: 'restyle',
	      args: ['currentvalue.suffix', '\t\tColor is amber']
            }, {
              label: '0.8',
              method: 'restyle',
	      args: ['currentvalue.suffix', '\t\tColor is amber']
            }, {
              label: '0.9',
              method: 'restyle',
	      args: ['currentvalue.suffix', '\t\tColor is amber']
            }, {
              label: '1.0',
              method: 'restyle',
              args: ['currentvalue.suffix', '\t\tColor is brown']
            }],
	    }],
	};

var myPlot = document.getElementById('InteractiveElement3');
//Plotly.newPlot("InteractiveElement3", [table, trace1, trace2, trace3, very_small, very_small_interval, very_small_projection_left, very_small_projection_right, small, small_interval, small_projection_left, small_projection_right, medium, medium_interval, medium_projection_left, medium_projection_right, large, large_interval, large_projection_left, large_projection_right, very_large, very_large_interval, very_large_projection_left, very_large_projection_right], layout, {displayModeBar: false});

Plotly.newPlot("InteractiveElement3", [table, trace1, trace2, trace3, very_small, very_small_interval, small, small_interval, medium, medium_interval, large, large_interval, very_large, very_large_interval], layout, {displayModeBar: false});

myPlot.on('plotly_sliderchange', function(sliderData){
var very_small = {x: [1882.34, 1882.34, 3243.81, 3632.81, 1882.34],
            y: [0, 1, 1, 0, 0],
            mode: 'none',
	    opacity: 0.25, 		    
            type: 'scatter',
	    fill: 'toself',
	    name: 'Very small',
            marker: {color: 'blue'},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			};

var very_small_interval = {x: [1882.34, 3438.31],
            y: [0.5, 0.5],
            type: 'scatter',
            mode: 'lines+markers',
	    opacity: 0.35, 
            marker: {color: 'blue'},
            showlegend: false,
    	    xaxis: 'x2',
	    yaxis: 'y2',
			};

var small = {
            x: [3243.81, 3632.81, 4799.78, 5188.78, 3243.81],
            y: [0, 1, 1, 0, 0],
            mode: 'none',
	    opacity: 0.25, 
	    color: 'orange',
            type: 'scatter',
	    fill: 'toself',
	    name: 'Small',
    	    xaxis: 'x2',
	    yaxis: 'y2',
        };

var small_interval = {x: [3438.31, 4994.28],
            y: [0.5, 0.5],
            type: 'scatter',
            mode: 'lines+markers',
	    opacity: 0.35, 
            marker: {color: 'orange'},
            showlegend: false,
    	    xaxis: 'x2',
	    yaxis: 'y2',
			};

var medium = {
            x: [4799.78, 5188.78, 6355.75, 6744.75, 4799.78],
            y: [0, 1, 1, 0, 0],
            mode: 'none',
		    opacity: 0.25, 
		    color: 'yellow',
            type: 'scatter',
		    fill: 'toself',
			name: 'Medium',
    	    xaxis: 'x2',
	    yaxis: 'y2',
        };

var medium_interval = {x: [4994.28, 6550.26],
            y: [0.5, 0.5],
            type: 'scatter',
            mode: 'lines+markers',
	    opacity: 0.35, 
            marker: {color: 'red'},
            showlegend: false,
    	    xaxis: 'x2',
	    yaxis: 'y2',
			};

var large = {
            x: [6355.75, 6744.75, 7911.72, 8300.72, 6355.75],
            y: [0, 1, 1, 0, 0],
            mode: 'none',
		    opacity: 0.25, 
		    color: 'yellow',
            type: 'scatter',
		    fill: 'toself',
			name: 'Large',
    	    xaxis: 'x2',
	    yaxis: 'y2',
        };

var large_interval = {x: [6550.26, 8106.23],
            y: [0.5, 0.5],
            type: 'scatter',
            mode: 'lines+markers',
	    opacity: 0.35, 
            marker: {color: 'magenta'},
            showlegend: false,
    	    xaxis: 'x2',
	    yaxis: 'y2',
			};

var very_large = {
            x: [7911.72, 8300.72, 9662.20, 9662.20, 7911.72],
            y: [0, 1, 1, 0, 0],
            mode: 'none',
		    opacity: 0.25, 
		    color: 'yellow',
            type: 'scatter',
		    fill: 'toself',
			name: 'Very large',
    	    xaxis: 'x2',
	    yaxis: 'y2',
        }

var very_large_interval = {x: [8106.23, 9662.20],
            y: [0.5, 0.5],
            type: 'scatter',
            mode: 'lines+markers',
	    opacity: 0.35, 
            marker: {color: 'grey'},
            showlegend: false,
    	    xaxis: 'x2',
	    yaxis: 'y2',
			};

  console.log('Slider set to', sliderData.slider.active);
  while(InteractiveElement3.data.length>0)
  {
      Plotly.deleteTraces(InteractiveElement3, [0]);
  }
  if (sliderData.slider.active == 0)
    {console.log('alpha-cut = 0');
     var table = { type: 'table',
       header: {
       values: [["<b>Partition interval</b>"], ["<b>Term</b>"], ["<b>Term interval</b>"], ["<b>Intersection</b>"], ["<b>Union</b>"], ["<b>Similarity</b>"]],
       align: "center",
       line: {width: 1, color: 'black'},
       fill: {color: "grey"},
       font: {family: "Arial", size: 12, color: "white"}
       },
       cells: {
         values: [["[3000, 6500]", "[3000, 6500]", "[3000, 6500]", "[3000, 6500]", "[3000, 6500]"], 
	              ["Very small", "<b>Small</b>", "Medium", "Large", "Very large"], 
                  ["[1882.34, 3438.31]", "[3438.31, 4994.28]", "[4994.28, 6550.26]", "[6550.26, 8106.23]", "[8106.23, 9662.20]"], 
                  ["438.31", "1555.97", "1505.72", "0.00", "0.00"],       
                  ["4617.66", "3500.00", "3550.26", "5106.23", "6662.20"], 
                  ["0.095", "<b>0.445</b>", "0.424", "0", "0"]],
         align: "center",
         line: {color: "black", width: 1},
         font: {family: "Arial", size: 11, color: ["black"]},
         //domain: {x: [0, 0.5], y: [0.5,1]},
         //domain: {column: 0, row: 0}
       }
     }
     Plotly.addTraces(InteractiveElement3, [table, 
	{
            type: 'scatter',  // all "scatter" attributes: https://plotly.com/javascript/reference/#scatter
            mode: 'lines',
            x: [1882.34, 9662.20],     // more about "x": #scatter-x
            y: [0, 0],     // #scatter-y
            marker: {         // marker is an object, valid marker keys: #scatter-marker
                color: 'rgb(16, 32, 77)' // more about "marker.color": #scatter-marker-color
            },
            showlegend: false,
	    line: {dash: "dash"},
            xaxis: 'x2',
            yaxis: 'y2',
        },
	{
            type: 'scatter',  // all "scatter" attributes: https://plotly.com/javascript/reference/#scatter
            x: [3000, 4500, 6300, 6500, 3000],     // more about "x": #scatter-x
            y: [0, 1, 1, 0, 0],     // #scatter-y
            marker: {         // marker is an object, valid marker keys: #scatter-marker
                color: 'rgb(16, 32, 77)' // more about "marker.color": #scatter-marker-color
            },
            showlegend: false,
            xaxis: 'x2',
            yaxis: 'y2',
        },
        {
            type: 'scatter',  // all "scatter" attributes: https://plotly.com/javascript/reference/#scatter
            x: [3000, 6500],     // more about "x": #scatter-x
            y: [0, 0],     // #scatter-y
            marker: {         // marker is an object, valid marker keys: #scatter-marker
                color: 'green' // more about "marker.color": #scatter-marker-color
            },
            showlegend: false,
	    fill: 'tozerox',
            xaxis: 'x2',
            yaxis: 'y2',
        },
	{   x: [1882.34, 3000],
            y: [0.5, 0],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'blue'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [3438.31, 6500],
            y: [0.5, 0],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'blue'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [3438.31, 3000],
            y: [0.5, 0],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'orange'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [4994.28, 6500],
            y: [0.5, 0],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'orange'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [4994.28, 3000],
            y: [0.5, 0],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'red'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [6550.26, 6500],
            y: [0.5, 0],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'red'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [6550.26, 3000],
            y: [0.5, 0],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'magenta'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [8106.23, 6500],
            y: [0.5, 0],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'magenta'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [8106.23, 3000],
            y: [0.5, 0],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'grey'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [9662.20, 6500],
            y: [0.5, 0],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'grey'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
		very_small,
		very_small_interval,
		small,
		small_interval,
		medium,
		medium_interval,
		large,
		large_interval,
		very_large,
		very_large_interval]);
  }
  else if (sliderData.slider.active == 1)
    {console.log('alpha-cut = 0.1');
     var table = { type: 'table',
       header: {
       values: [["<b>Partition interval</b>"], ["<b>Term</b>"], ["<b>Term interval</b>"], ["<b>Intersection</b>"], ["<b>Union</b>"], ["<b>Similarity</b>"]],
       align: "center",
       line: {width: 1, color: 'black'},
       fill: {color: "grey"},
       font: {family: "Arial", size: 12, color: "white"}
       },
       cells: {
         values: [["[3150, 6480]", "[3150, 6480]", "[3150, 6480]", "[3150, 6480]", "[3150, 6480]"], 
	          ["Very small", "<b>Small</b>", "Medium", "Large", "Very large"], 
                  ["[1882.34, 3438.31]", "[3438.31, 4994.28]", "[4994.28, 6550.26]", "[6550.26, 8106.23]", "[8106.23, 9662.20]"], 
                  ["288.31", "1555.97", "1485.72", "0.00", "0.00"],       
                  ["4597.66", "3330.00", "3400.26", "4956.23", "6512.20"], 
                  ["0.063", "<b>0.467</b>", "0.437", "0", "0"]],
         align: "center",
         line: {color: "black", width: 1},
         font: {family: "Arial", size: 11, color: ["black"]},
         //domain: {x: [0, 0.5], y: [0.5,1]},
         //domain: {column: 0, row: 0}
       }
     }
     Plotly.addTraces(InteractiveElement3, [table, 
	{
            type: 'scatter',  // all "scatter" attributes: https://plotly.com/javascript/reference/#scatter
            mode: 'lines',
            x: [1882.34, 9662.20],     // more about "x": #scatter-x
            y: [0.1, 0.1],     // #scatter-y
            marker: {         // marker is an object, valid marker keys: #scatter-marker
                color: 'rgb(16, 32, 77)' // more about "marker.color": #scatter-marker-color
            },
            showlegend: false,
	    line: {dash: "dash"},
            xaxis: 'x2',
            yaxis: 'y2',
        },
	{
            type: 'scatter',  // all "scatter" attributes: https://plotly.com/javascript/reference/#scatter
            x: [3000, 4500, 6300, 6500, 3000],     // more about "x": #scatter-x
            y: [0, 1, 1, 0, 0],     // #scatter-y
            marker: {         // marker is an object, valid marker keys: #scatter-marker
                color: 'rgb(16, 32, 77)' // more about "marker.color": #scatter-marker-color
            },
            showlegend: false,
            xaxis: 'x2',
            yaxis: 'y2',
        },
       {
            type: 'scatter',  // all "scatter" attributes: https://plotly.com/javascript/reference/#scatter
            x: [3000, 3150, 6480, 6500, 3000],     // more about "x": #scatter-x
            y: [0, 0.1, 0.1, 0, 0],     // #scatter-y
            marker: {         // marker is an object, valid marker keys: #scatter-marker
                color: 'green' // more about "marker.color": #scatter-marker-color
            },
            showlegend: false,
	    fill: 'tozerox',
            xaxis: 'x2',
            yaxis: 'y2',
        },
	{   x: [1882.34, 3150],
            y: [0.5, 0.1],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'blue'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [3438.31, 6480],
            y: [0.5, 0.1],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'blue'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [3438.31, 3150],
            y: [0.5, 0.1],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'orange'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [4994.28, 6480],
            y: [0.5, 0.1],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'orange'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [4994.28, 3150],
            y: [0.5, 0.1],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'red'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [6550.26, 6480],
            y: [0.5, 0.1],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'red'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [6550.26, 3150],
            y: [0.5, 0.1],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'magenta'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [8106.23, 6480],
            y: [0.5, 0.1],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'magenta'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [8106.23, 3150],
            y: [0.5, 0.1],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'grey'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [9662.20, 6480],
            y: [0.5, 0.1],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'grey'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
		very_small,
		very_small_interval,
		small,
		small_interval,
		medium,
		medium_interval,
		large,
		large_interval,
		very_large,
		very_large_interval]);
	}
  else if (sliderData.slider.active == 2)
    {console.log('alpha-cut = 0.2');
     var table = { type: 'table',
       header: {
         values: [["<b>Partition interval</b>"], ["<b>Term</b>"], ["<b>Term interval</b>"], ["<b>Intersection</b>"], ["<b>Union</b>"], ["<b>Similarity</b>"]],
         align: "center",
         line: {width: 1, color: 'black'},
         fill: {color: "grey"},
         font: {family: "Arial", size: 12, color: "white"}
       },
       cells: {
         values: [["[3300, 6460]", "[3300, 6460]", "[3300, 6460]", "[3300, 6460]", "[3300, 6460]"], 
	          ["Very small", "<b>Small</b>", "Medium", "Large", "Very large"], 
                  ["[1882.34, 3438.31]", "[3438.31, 4994.28]", "[4994.28, 6550.26]", "[6550.26, 8106.23]", "[8106.23, 9662.20]"], 
                  ["138.31", "1555.97", "1465.72", "0.00", "0.00"],       
                  ["4577.66", "3160.00", "3250.26", "4806.23", "6362.20"], 
                  ["0.030", "<b>0.492</b>", "0.451", "0", "0"]],
         align: "center",
         line: {color: "black", width: 1},
         font: {family: "Arial", size: 11, color: ["black"]},
         xaxis: 'x1',
         yaxis: 'y1',
         domain: {x: [0, 0.5], y: [0.5,1]},
         //domain: {column: 0, row: 0},
       }
     }
     Plotly.addTraces(InteractiveElement3, [table, 
	{
            type: 'scatter',  // all "scatter" attributes: https://plotly.com/javascript/reference/#scatter
            mode: 'lines',
            x: [1882.34, 9662.20],     // more about "x": #scatter-x
            y: [0.2, 0.2],     // #scatter-y
            marker: {         // marker is an object, valid marker keys: #scatter-marker
                color: 'rgb(16, 32, 77)' // more about "marker.color": #scatter-marker-color
            },
	    line: {dash: "dash"},
            showlegend: false,
            xaxis: 'x2',
            yaxis: 'y2',
        },
	{
            type: 'scatter',  // all "scatter" attributes: https://plotly.com/javascript/reference/#scatter
            x: [3000, 4500, 6300, 6500, 3000],     // more about "x": #scatter-x
            y: [0, 1, 1, 0, 0],     // #scatter-y
            marker: {         // marker is an object, valid marker keys: #scatter-marker
                color: 'rgb(16, 32, 77)' // more about "marker.color": #scatter-marker-color
            },
            showlegend: false,
            xaxis: 'x2',
            yaxis: 'y2',
        },
       {
            type: 'scatter',  // all "scatter" attributes: https://plotly.com/javascript/reference/#scatter			
            x: [3000, 3300, 6460, 6500, 3000],     // more about "x": #scatter-x
            y: [0, 0.2, 0.2, 0, 0],     // #scatter-y
            marker: {         // marker is an object, valid marker keys: #scatter-marker
                color: 'green' // more about "marker.color": #scatter-marker-color
            },
            showlegend: false,
	    fill: 'tozerox',
            xaxis: 'x2',
            yaxis: 'y2',
        },
	{   x: [1882.34, 3300],
            y: [0.5, 0.2],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'blue'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [3438.31, 6460],
            y: [0.5, 0.2],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'blue'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [3438.31, 3300],
            y: [0.5, 0.2],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'orange'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [4994.28, 6460],
            y: [0.5, 0.2],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'orange'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [4994.28, 3300],
            y: [0.5, 0.2],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'red'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [6550.26, 6460],
            y: [0.5, 0.2],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'red'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [6550.26, 3300],
            y: [0.5, 0.2],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'magenta'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [8106.23, 6460],
            y: [0.5, 0.2],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'magenta'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [8106.23, 3300],
            y: [0.5, 0.2],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'grey'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [9662.20, 6460],
            y: [0.5, 0.2],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'grey'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
		very_small,
		very_small_interval,
		small,
		small_interval,
		medium,
		medium_interval,
		large,
		large_interval,
		very_large,
		very_large_interval]);
    }
  else if (sliderData.slider.active == 3)
    {console.log('alpha-cut = 0.3');
     var table = { type: 'table',
       header: {
         values: [["<b>Partition interval</b>"], ["<b>Term</b>"], ["<b>Term interval</b>"], ["<b>Intersection</b>"], ["<b>Union</b>"], ["<b>Similarity</b>"]],
         align: "center",
         line: {width: 1, color: 'black'},
         fill: {color: "grey"},
         font: {family: "Arial", size: 12, color: "white"}
       },
       cells: {
         values: [["[3450, 6440]", "[3450, 6440]", "[3450, 6440]", "[3450, 6440]", "[3450, 6440]"], 
	          ["Very small", "<b>Small</b>", "Medium", "Large", "Very large"], 
                  ["[1882.34, 3438.31]", "[3438.31, 4994.28]", "[4994.28, 6550.26]", "[6550.26, 8106.23]", "[8106.23, 9662.20]"], 
                  ["0.00", "1544.28", "1445.72", "0.00", "0.00"],       
                  ["4557.66", "3001.69", "3100.26", "4656.23", "6212.20"], 
                  ["0", "<b>0.514</b>", "0.466", "0", "0"]],
         align: "center",
         line: {color: "black", width: 1},
         font: {family: "Arial", size: 11, color: ["black"]},
         xaxis: 'x1',
         yaxis: 'y1',
         domain: {x: [0, 0.5], y: [0.5,1]},
         //domain: {column: 0, row: 0},
       }
     }
     Plotly.addTraces(InteractiveElement3, [table, 
	{
            type: 'scatter',  // all "scatter" attributes: https://plotly.com/javascript/reference/#scatter
            mode: 'lines',
            x: [1882.34, 9662.20],     // more about "x": #scatter-x
            y: [0.3, 0.3],     // #scatter-y
            marker: {         // marker is an object, valid marker keys: #scatter-marker
                color: 'rgb(16, 32, 77)' // more about "marker.color": #scatter-marker-color
            },
            showlegend: false,
	    line: {dash: "dash"},
            xaxis: 'x2',
            yaxis: 'y2',
        },
	{
            type: 'scatter',  // all "scatter" attributes: https://plotly.com/javascript/reference/#scatter
            x: [3000, 4500, 6300, 6500, 3000],     // more about "x": #scatter-x
            y: [0, 1, 1, 0, 0],     // #scatter-y
            marker: {         // marker is an object, valid marker keys: #scatter-marker
                color: 'rgb(16, 32, 77)' // more about "marker.color": #scatter-marker-color
            },
            showlegend: false,
            xaxis: 'x2',
            yaxis: 'y2',
        },
       {
            type: 'scatter',  // all "scatter" attributes: https://plotly.com/javascript/reference/#scatter			
            x: [3000, 3450, 6440, 6500, 3000],     // more about "x": #scatter-x
            y: [0, 0.3, 0.3, 0, 0],     // #scatter-y
            marker: {         // marker is an object, valid marker keys: #scatter-marker
                color: 'green' // more about "marker.color": #scatter-marker-color
            },
            xaxis: 'x2',
            yaxis: 'y2',
            showlegend: false,
	    fill: 'tozerox',
        },
	{   x: [1882.34, 3450],
            y: [0.5, 0.3],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'blue'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [3438.31, 6440],
            y: [0.5, 0.3],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'blue'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [3438.31, 3450],
            y: [0.5, 0.3],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'orange'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [4994.28, 6440],
            y: [0.5, 0.3],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'orange'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [4994.28, 3450],
            y: [0.5, 0.3],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'red'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [6550.26, 6440],
            y: [0.5, 0.3],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'red'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [6550.26, 3450],
            y: [0.5, 0.3],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'magenta'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [8106.23, 6440],
            y: [0.5, 0.3],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'magenta'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [8106.23, 3450],
            y: [0.5, 0.3],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'grey'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [9662.20, 6440],
            y: [0.5, 0.3],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'grey'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
		very_small,
		very_small_interval,
		small,
		small_interval,
		medium,
		medium_interval,
		large,
		large_interval,
		very_large,
		very_large_interval]);
    }
  else if (sliderData.slider.active == 4)
    {console.log('alpha-cut = 0.4');
     var table = { type: 'table',
       header: {
         values: [["<b>Partition interval</b>"], ["<b>Term</b>"], ["<b>Term interval</b>"], ["<b>Intersection</b>"], ["<b>Union</b>"], ["<b>Similarity</b>"]],
         align: "center",
         line: {width: 1, color: 'black'},
         fill: {color: "grey"},
         font: {family: "Arial", size: 12, color: "white"}
       },
       cells: {
         values: [["[3600, 6420]", "[3600, 6420]", "[3600, 6420]", "[3600, 6420]", "[3600, 6420]"], 
	          ["Very small", "Small", "<b>Medium</b>", "Large", "Very large"], 
                  ["[1882.34, 3438.31]", "[3438.31, 4994.28]", "[4994.28, 6550.26]", "[6550.26, 8106.23]", "[8106.23, 9662.20]"], 
                  ["0.00", "1394.28", "1425.72", "0.00", "0.00"],       
                  ["4537.66", "2981.69", "2950.26", "4506.23", "6062.20"], 
                  ["0", "0.468", "<b>0.483</b>", "0", "0"]],
         align: "center",
         line: {color: "black", width: 1},
         font: {family: "Arial", size: 11, color: ["black"]},
         xaxis: 'x1',
         yaxis: 'y1',
         domain: {x: [0, 0.5], y: [0.5,1]},
         //domain: {column: 0, row: 0},
       }
     }
     Plotly.addTraces(InteractiveElement3, [table, 
	{
            type: 'scatter',  // all "scatter" attributes: https://plotly.com/javascript/reference/#scatter
            mode: 'lines',
            x: [1882.34, 9662.20],     // more about "x": #scatter-x
            y: [0.4, 0.4],     // #scatter-y
            marker: {         // marker is an object, valid marker keys: #scatter-marker
                color: 'rgb(16, 32, 77)' // more about "marker.color": #scatter-marker-color
            },
	    line: {dash: "dash"},
            showlegend: false,
            xaxis: 'x2',
            yaxis: 'y2',
        },
	{
            type: 'scatter',  // all "scatter" attributes: https://plotly.com/javascript/reference/#scatter
            x: [3000, 4500, 6300, 6500, 3000],     // more about "x": #scatter-x
            y: [0, 1, 1, 0, 0],     // #scatter-y
            marker: {         // marker is an object, valid marker keys: #scatter-marker
                color: 'rgb(16, 32, 77)' // more about "marker.color": #scatter-marker-color
            },
            showlegend: false,
            xaxis: 'x2',
            yaxis: 'y2',
        },
       {
            type: 'scatter',  // all "scatter" attributes: https://plotly.com/javascript/reference/#scatter			
            x: [3000, 3600, 6420, 6500, 3000],     // more about "x": #scatter-x
            y: [0, 0.4, 0.4, 0, 0],     // #scatter-y
            marker: {         // marker is an object, valid marker keys: #scatter-marker
                color: 'green' // more about "marker.color": #scatter-marker-color
            },
            showlegend: false,
            xaxis: 'x2',
            yaxis: 'y2',
	    fill: 'tozerox',
        },
	{   x: [1882.34, 3600],
            y: [0.5, 0.4],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'blue'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [3438.31, 6420],
            y: [0.5, 0.4],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'blue'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [3438.31, 3600],
            y: [0.5, 0.4],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'orange'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [4994.28, 6420],
            y: [0.5, 0.4],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'orange'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [4994.28, 3600],
            y: [0.5, 0.4],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'red'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [6550.26, 6420],
            y: [0.5, 0.4],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'red'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [6550.26, 3600],
            y: [0.5, 0.4],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'magenta'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [8106.23, 6420],
            y: [0.5, 0.4],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'magenta'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [8106.23, 3600],
            y: [0.5, 0.4],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'grey'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [9662.20, 6420],
            y: [0.5, 0.4],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'grey'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
		very_small,
		very_small_interval,
		small,
		small_interval,
		medium,
		medium_interval,
		large,
		large_interval,
		very_large,
		very_large_interval]);
    }
  else if (sliderData.slider.active == 5)
    {console.log('alpha-cut = 0.5');
     var table = { type: 'table',
       header: {
         values: [["<b>Partition interval</b>"], ["<b>Term</b>"], ["<b>Term interval</b>"], ["<b>Intersection</b>"], ["<b>Union</b>"], ["<b>Similarity</b>"]],
         align: "center",
         line: {width: 1, color: 'black'},
         fill: {color: "grey"},
         font: {family: "Arial", size: 12, color: "white"}
       },
       cells: {
         values: [["[3750, 6400]", "[3750, 6400]", "[3750, 6400]", "[3750, 6400]", "[3750, 6400]"], 
	          ["Very small", "Small", "<b>Medium</b>", "Large", "Very large"], 
                  ["[1882.34, 3438.31]", "[3438.31, 4994.28]", "[4994.28, 6550.26]", "[6550.26, 8106.23]", "[8106.23, 9662.20]"], 
                  ["0.00", "1244.28", "1405.72", "0.00", "0.00"],       
                  ["4517.66", "2961.69", "2800.26", "4356.23", "5912.20"], 
                  ["0", "0.420", "<b>0.502</b>", "0", "0"]],
         align: "center",
         line: {color: "black", width: 1},
         font: {family: "Arial", size: 11, color: ["black"]},
         xaxis: 'x1',
         yaxis: 'y1',
         domain: {x: [0, 0.5], y: [0.5,1]},
         //domain: {column: 0, row: 0},
       }
     }
     Plotly.addTraces(InteractiveElement3, [table, 
	{
            type: 'scatter',  // all "scatter" attributes: https://plotly.com/javascript/reference/#scatter
            mode: 'lines',
            x: [1882.34, 9662.20],     // more about "x": #scatter-x
            y: [0.5, 0.5],     // #scatter-y
            marker: {         // marker is an object, valid marker keys: #scatter-marker
                color: 'rgb(16, 32, 77)' // more about "marker.color": #scatter-marker-color
            },
            showlegend: false,
	    line: {dash: "dash"},
            xaxis: 'x2',
            yaxis: 'y2',
        },
	{
            type: 'scatter',  // all "scatter" attributes: https://plotly.com/javascript/reference/#scatter
            x: [3000, 4500, 6300, 6500, 3000],     // more about "x": #scatter-x
            y: [0, 1, 1, 0, 0],     // #scatter-y
            marker: {         // marker is an object, valid marker keys: #scatter-marker
                color: 'rgb(16, 32, 77)' // more about "marker.color": #scatter-marker-color
            },
            showlegend: false,
            xaxis: 'x2',
            yaxis: 'y2',
        },
       {
            type: 'scatter',  // all "scatter" attributes: https://plotly.com/javascript/reference/#scatter			
            x: [3000, 3750, 6400, 6500, 3000],     // more about "x": #scatter-x
            y: [0, 0.5, 0.5, 0, 0],     // #scatter-y
            marker: {         // marker is an object, valid marker keys: #scatter-marker
                color: 'green' // more about "marker.color": #scatter-marker-color
            },
            showlegend: false,
	    fill: 'tozerox',
            xaxis: 'x2',
            yaxis: 'y2',
        },
		very_small,
		very_small_interval,
		small,
		small_interval,
		medium,
		medium_interval,
		large,
		large_interval,
		very_large,
		very_large_interval]);
    }
  else if (sliderData.slider.active == 6)
    {console.log('alpha-cut = 0.6');
     var table = { type: 'table',
       header: {
         values: [["<b>Partition interval</b>"], ["<b>Term</b>"], ["<b>Term interval</b>"], ["<b>Intersection</b>"], ["<b>Union</b>"], ["<b>Similarity</b>"]],
         align: "center",
         line: {width: 1, color: 'black'},
         fill: {color: "grey"},
         font: {family: "Arial", size: 12, color: "white"}
       },
       cells: {
         values: [["[3900, 6380]", "[3900, 6380]", "[3900, 6380]", "[3900, 6380]", "[3900, 6380]"], 
	          ["Very small", "Small", "<b>Medium</b>", "Large", "Very large"], 
                  ["[1882.34, 3438.31]", "[3438.31, 4994.28]", "[4994.28, 6550.26]", "[6550.26, 8106.23]", "[8106.23, 9662.20]"], 
                  ["0.00", "1385.72", "1385.72", "0.00", "0.00"],       
                  ["4497.66", "2941.69", "2650.26", "4206.23", "5762.20"], 
                  ["0", "0.372", "<b>0.523</b>", "0", "0"]],
         align: "center",
         line: {color: "black", width: 1},
         font: {family: "Arial", size: 11, color: ["black"]},
         xaxis: 'x1',
         yaxis: 'y1',
         domain: {x: [0, 0.5], y: [0.5,1]},
         //domain: {column: 0, row: 0},
       }
     }
     Plotly.addTraces(InteractiveElement3, [table, 
	{
            type: 'scatter',  // all "scatter" attributes: https://plotly.com/javascript/reference/#scatter
            mode: 'lines',
            x: [1882.34, 9662.20],     // more about "x": #scatter-x
            y: [0.6, 0.6],     // #scatter-y
            marker: {         // marker is an object, valid marker keys: #scatter-marker
                color: 'rgb(16, 32, 77)' // more about "marker.color": #scatter-marker-color
            },
	    line: {dash: "dash"},
            showlegend: false,
            xaxis: 'x2',
            yaxis: 'y2',
        },
	{
            type: 'scatter',  // all "scatter" attributes: https://plotly.com/javascript/reference/#scatter
            x: [3000, 4500, 6300, 6500, 3000],     // more about "x": #scatter-x
            y: [0, 1, 1, 0, 0],     // #scatter-y
            marker: {         // marker is an object, valid marker keys: #scatter-marker
                color: 'rgb(16, 32, 77)' // more about "marker.color": #scatter-marker-color
            },
            showlegend: false,
            xaxis: 'x2',
            yaxis: 'y2',
        },
       {
            type: 'scatter',  // all "scatter" attributes: https://plotly.com/javascript/reference/#scatter			
            x: [3000, 3900, 6380, 6500, 3000],     // more about "x": #scatter-x
            y: [0, 0.6, 0.6, 0, 0],     // #scatter-y
            marker: {         // marker is an object, valid marker keys: #scatter-marker
                color: 'green' // more about "marker.color": #scatter-marker-color
            },
			fill: 'tozerox',
            showlegend: false,
            xaxis: 'x2',
            yaxis: 'y2',
        },
	{   x: [1882.34, 3900],
            y: [0.5, 0.6],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'blue'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [3438.31, 6380],
            y: [0.5, 0.6],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'blue'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [3438.31, 3900],
            y: [0.5, 0.6],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'orange'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [4994.28, 6380],
            y: [0.5, 0.6],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'orange'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [4994.28, 3900],
            y: [0.5, 0.6],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'red'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [6550.26, 6380],
            y: [0.5, 0.6],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'red'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [6550.26, 3900],
            y: [0.5, 0.6],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'magenta'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [8106.23, 6380],
            y: [0.5, 0.6],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'magenta'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [8106.23, 3900],
            y: [0.5, 0.6],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'grey'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [9662.20, 6380],
            y: [0.5, 0.6],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'grey'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
		very_small,
		very_small_interval,
		small,
		small_interval,
		medium,
		medium_interval,
		large,
		large_interval,
		very_large,
		very_large_interval]);
    }
  else if (sliderData.slider.active == 7)
    {console.log('alpha-cut = 0.7');
     var table = { type: 'table',
       header: {
         values: [["<b>Partition interval</b>"], ["<b>Term</b>"], ["<b>Term interval</b>"], ["<b>Intersection</b>"], ["<b>Union</b>"], ["<b>Similarity</b>"]],
         align: "center",
         line: {width: 1, color: 'black'},
         fill: {color: "grey"},
         font: {family: "Arial", size: 12, color: "white"}
       },
       cells: {
         values: [["[4050, 6360]", "[4050, 6360]", "[4050, 6360]", "[4050, 6360]", "[4050, 6360]"], 
	          ["Very small", "Small", "<b>Medium</b>", "Large", "Very large"], 
                  ["[1882.34, 3438.31]", "[3438.31, 4994.28]", "[4994.28, 6550.26]", "[6550.26, 8106.23]", "[8106.23, 9662.20]"], 
                  ["0.00", "944.28", "1365.72", "0.00", "0.00"],       
                  ["4477.66", "2921.69", "2500.26", "4056.23", "5612.20"], 
                  ["0", "0.323", "<b>0.546</b>", "0", "0"]],
         align: "center",
         line: {color: "black", width: 1},
         font: {family: "Arial", size: 11, color: ["black"]},
         xaxis: 'x1',
         yaxis: 'y1',
         domain: {x: [0, 0.5], y: [0.5,1]},
         //domain: {column: 0, row: 0},
       }
     }
     Plotly.addTraces(InteractiveElement3, [table, 
	{
            type: 'scatter',  // all "scatter" attributes: https://plotly.com/javascript/reference/#scatter
            mode: 'lines',
            x: [1882.34, 9662.20],     // more about "x": #scatter-x
            y: [0.7, 0.7],     // #scatter-y
            marker: {         // marker is an object, valid marker keys: #scatter-marker
                color: 'rgb(16, 32, 77)' // more about "marker.color": #scatter-marker-color
            },
	    line: {dash: "dash"},
            showlegend: false,
            xaxis: 'x2',
            yaxis: 'y2',
        },
	{
            type: 'scatter',  // all "scatter" attributes: https://plotly.com/javascript/reference/#scatter
            x: [3000, 4500, 6300, 6500, 3000],     // more about "x": #scatter-x
            y: [0, 1, 1, 0, 0],     // #scatter-y
            marker: {         // marker is an object, valid marker keys: #scatter-marker
                color: 'rgb(16, 32, 77)' // more about "marker.color": #scatter-marker-color
            },
            showlegend: false,
            xaxis: 'x2',
            yaxis: 'y2',
        },
       {
            type: 'scatter',  // all "scatter" attributes: https://plotly.com/javascript/reference/#scatter			
            x: [3000, 4050, 6360, 6500, 3000],     // more about "x": #scatter-x
            y: [0, 0.7, 0.7, 0, 0],     // #scatter-y
            marker: {         // marker is an object, valid marker keys: #scatter-marker
                color: 'green' // more about "marker.color": #scatter-marker-color
            },
	    fill: 'tozerox',
            showlegend: false,
            xaxis: 'x2',
            yaxis: 'y2',
        },
	{   x: [1882.34, 4050],
            y: [0.5, 0.7],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'blue'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [3438.31, 6360],
            y: [0.5, 0.7],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'blue'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [3438.31, 4050],
            y: [0.5, 0.7],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'orange'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [4994.28, 6360],
            y: [0.5, 0.7],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'orange'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [4994.28, 4050],
            y: [0.5, 0.7],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'red'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [6550.26, 6360],
            y: [0.5, 0.7],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'red'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [6550.26, 4050],
            y: [0.5, 0.7],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'magenta'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [8106.23, 6360],
            y: [0.5, 0.7],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'magenta'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [8106.23, 4050],
            y: [0.5, 0.7],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'grey'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [9662.20, 6360],
            y: [0.5, 0.7],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'grey'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
		very_small,
		very_small_interval,
		small,
		small_interval,
		medium,
		medium_interval,
		large,
		large_interval,
		very_large,
		very_large_interval]);
    }
  else if (sliderData.slider.active == 8)
     {var table = { type: 'table',
       header: {
         values: [["<b>Partition interval</b>"], ["<b>Term</b>"], ["<b>Term interval</b>"], ["<b>Intersection</b>"], ["<b>Union</b>"], ["<b>Similarity</b>"]],
         align: "center",
         line: {width: 1, color: 'black'},
         fill: {color: "grey"},
         font: {family: "Arial", size: 12, color: "white"}
       },
       cells: {
         values: [["[4200, 6340]", "[4200, 6340]", "[4200, 6340]", "[4200, 6340]", "[4200, 6340]"], 
	          ["Very small", "Small", "<b>Medium</b>", "Large", "Very large"], 
                  ["[1882.34, 3438.31]", "[3438.31, 4994.28]", "[4994.28, 6550.26]", "[6550.26, 8106.23]", "[8106.23, 9662.20]"], 
                  ["0.00", "794.28", "1345.72", "0.00", "0.00"],       
                  ["4457.66", "2901.69", "2350.26", "3906.23", "5462.20"], 
                  ["0", "0.274", "<b>0.573</b>", "0", "0"]],
         align: "center",
         line: {color: "black", width: 1},
         font: {family: "Arial", size: 11, color: ["black"]},
         xaxis: 'x1',
         yaxis: 'y1',
         domain: {x: [0, 0.5], y: [0.5,1]},
         //domain: {column: 0, row: 0},
       }
     }
     console.log('alpha-cut = 0.8');
     Plotly.addTraces(InteractiveElement3, [table, 
	{
            type: 'scatter',  // all "scatter" attributes: https://plotly.com/javascript/reference/#scatter
            mode: 'lines',
            x: [1882.34, 9662.20],     // more about "x": #scatter-x
            y: [0.8, 0.8],     // #scatter-y
            marker: {         // marker is an object, valid marker keys: #scatter-marker
                color: 'rgb(16, 32, 77)' // more about "marker.color": #scatter-marker-color
            },
	    line: {dash: "dash"},
            showlegend: false,
            xaxis: 'x2',
            yaxis: 'y2',
        },
	{
            type: 'scatter',  // all "scatter" attributes: https://plotly.com/javascript/reference/#scatter
            x: [3000, 4500, 6300, 6500, 3000],     // more about "x": #scatter-x
            y: [0, 1, 1, 0, 0],     // #scatter-y
            marker: {         // marker is an object, valid marker keys: #scatter-marker
                color: 'rgb(16, 32, 77)' // more about "marker.color": #scatter-marker-color
            },
            showlegend: false,
            xaxis: 'x2',
            yaxis: 'y2',
        },
       {
            type: 'scatter',  // all "scatter" attributes: https://plotly.com/javascript/reference/#scatter			
            x: [3000, 4200, 6340, 6500, 3000],     // more about "x": #scatter-x
            y: [0, 0.8, 0.8, 0, 0],     // #scatter-y
            marker: {         // marker is an object, valid marker keys: #scatter-marker
                color: 'green' // more about "marker.color": #scatter-marker-color
            },
	    fill: 'tozerox',
            showlegend: false,
            xaxis: 'x2',
            yaxis: 'y2',
        },
	{   x: [1882.34, 4200],
            y: [0.5, 0.8],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'blue'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [3438.31, 6340],
            y: [0.5, 0.8],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'blue'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [3438.31, 4200],
            y: [0.5, 0.8],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'orange'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [4994.28, 6340],
            y: [0.5, 0.8],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'orange'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [4994.28, 4200],
            y: [0.5, 0.8],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'red'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [6550.26, 6340],
            y: [0.5, 0.8],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'red'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [6550.26, 4200],
            y: [0.5, 0.8],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'magenta'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [8106.23, 6340],
            y: [0.5, 0.8],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'magenta'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [8106.23, 4200],
            y: [0.5, 0.8],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'grey'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [9662.20, 6340],
            y: [0.5, 0.8],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'grey'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
		very_small,
		very_small_interval,
		small,
		small_interval,
		medium,
		medium_interval,
		large,
		large_interval,
		very_large,
		very_large_interval]);
    }
  else if (sliderData.slider.active == 9)
    {console.log('alpha-cut = 0.9');
     var table = { type: 'table',
       header: {
         values: [["<b>Partition interval</b>"], ["<b>Term</b>"], ["<b>Term interval</b>"], ["<b>Intersection</b>"], ["<b>Union</b>"], ["<b>Similarity</b>"]],
         align: "center",
         line: {width: 1, color: 'black'},
         fill: {color: "grey"},
         font: {family: "Arial", size: 12, color: "white"}
       },
       cells: {
         values: [["[4350, 6320]", "[4350, 6320]", "[4350, 6320]", "[4350, 6320]", "[4350, 6320]"], 
	          ["Very small", "Small", "<b>Medium</b>", "Large", "Very large"], 
                  ["[1882.34, 3438.31]", "[3438.31, 4994.28]", "[4994.28, 6550.26]", "[6550.26, 8106.23]", "[8106.23, 9662.20]"], 
                  ["0.00", "644.28", "1325.72", "0.00", "0.00"],       
                  ["4437.66", "2881.69", "2200.26", "3756.23", "5312.20"], 
                  ["0", "0.224", "<b>0.603</b>", "0", "0"]],
         align: "center",
         line: {color: "black", width: 1},
         font: {family: "Arial", size: 11, color: ["black"]},
         xaxis: 'x1',
         yaxis: 'y1',
         domain: {x: [0, 0.5], y: [0.5,1]},
         //domain: {column: 0, row: 0},
       }
     }
     Plotly.addTraces(InteractiveElement3, [table, 
	{
            type: 'scatter',  // all "scatter" attributes: https://plotly.com/javascript/reference/#scatter
            mode: 'lines',
            x: [1882.34, 9662.20],     // more about "x": #scatter-x
            y: [0.9, 0.9],     // #scatter-y
            marker: {         // marker is an object, valid marker keys: #scatter-marker
                color: 'rgb(16, 32, 77)' // more about "marker.color": #scatter-marker-color
            },
	    line: {dash: "dash"},
            showlegend: false,
            xaxis: 'x2',
            yaxis: 'y2',
        },
	{
            type: 'scatter',  // all "scatter" attributes: https://plotly.com/javascript/reference/#scatter
            x: [3000, 4500, 6300, 6500, 3000],     // more about "x": #scatter-x
            y: [0, 1, 1, 0, 0],     // #scatter-y
            marker: {         // marker is an object, valid marker keys: #scatter-marker
                color: 'rgb(16, 32, 77)' // more about "marker.color": #scatter-marker-color
            },
            showlegend: false,
            xaxis: 'x2',
            yaxis: 'y2',
        },
       {
            type: 'scatter',  // all "scatter" attributes: https://plotly.com/javascript/reference/#scatter			
            x: [3000, 4350, 6320, 6500, 3000],     // more about "x": #scatter-x
            y: [0, 0.9, 0.9, 0, 0],     // #scatter-y
            marker: {         // marker is an object, valid marker keys: #scatter-marker
                color: 'green' // more about "marker.color": #scatter-marker-color
            },
            showlegend: false,
            xaxis: 'x2',
            yaxis: 'y2',
	    fill: 'tozerox',
        },
	{   x: [1882.34, 4350],
            y: [0.5, 0.9],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'blue'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [3438.31, 6320],
            y: [0.5, 0.9],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'blue'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [3438.31, 4350],
            y: [0.5, 0.9],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'orange'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [4994.28, 6320],
            y: [0.5, 0.9],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'orange'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [4994.28, 4350],
            y: [0.5, 0.9],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'red'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [6550.26, 6320],
            y: [0.5, 0.9],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'red'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [6550.26, 4350],
            y: [0.5, 0.9],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'magenta'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [8106.23, 6320],
            y: [0.5, 0.9],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'magenta'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [8106.23, 4350],
            y: [0.5, 0.9],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'grey'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [9662.20, 6320],
            y: [0.5, 0.9],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'grey'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
		very_small,
		very_small_interval,
		small,
		small_interval,
		medium,
		medium_interval,
		large,
		large_interval,
		very_large,
		very_large_interval]);
    }
else if (sliderData.slider.active == 10)
    {console.log('alpha-cut = 1');
     var table = { type: 'table',
       header: {
         values: [["<b>Partition interval</b>"], ["<b>Term</b>"], ["<b>Term interval</b>"], ["<b>Intersection</b>"], ["<b>Union</b>"], ["<b>Similarity</b>"]],
         align: "center",
         line: {width: 1, color: 'black'},
         fill: {color: "grey"},
         font: {family: "Arial", size: 12, color: "white"}
       },
       cells: {
         values: [["[4500, 6300]", "[4500, 6300]", "[4500, 6300]", "[4500, 6300]", "[4500, 6300]"], 
	          ["Very small", "Small", "<b>Medium</b>", "Large", "Very large"], 
                  ["[1882.34, 3438.31]", "[3438.31, 4994.28]", "[4994.28, 6550.26]", "[6550.26, 8106.23]", "[8106.23, 9662.20]"], 
                  ["0.00", "494.28", "1305.72", "0.00", "0.00"],       
                  ["4417.66", "2861.69", "2050.26", "3606.23", "5162.20"], 
                  ["0", "0.173", "<b>0.637</b>", "0", "0"]],
         align: "center",
         line: {color: "black", width: 1},
         font: {family: "Arial", size: 11, color: ["black"]},
         xaxis: 'x1',
         yaxis: 'y1',
         domain: {x: [0, 0.5], y: [0.5,1]},
         //domain: {column: 0, row: 0},
       }
     }
     Plotly.addTraces(InteractiveElement3, [table, 
	{
            type: 'scatter',  // all "scatter" attributes: https://plotly.com/javascript/reference/#scatter
            mode: 'lines',
            x: [1882.34, 9662.20],     // more about "x": #scatter-x
            y: [1.0, 1.0],     // #scatter-y
            marker: {         // marker is an object, valid marker keys: #scatter-marker
                color: 'rgb(16, 32, 77)' // more about "marker.color": #scatter-marker-color
            },
	    line: {dash: "dash"},
            showlegend: false,
            xaxis: 'x2',
            yaxis: 'y2',
        },
	{
            type: 'scatter',  // all "scatter" attributes: https://plotly.com/javascript/reference/#scatter
            x: [3000, 4500, 6300, 6500, 3000],     // more about "x": #scatter-x
            y: [0, 1, 1, 0, 0],     // #scatter-y
            marker: {         // marker is an object, valid marker keys: #scatter-marker
                color: 'rgb(16, 32, 77)' // more about "marker.color": #scatter-marker-color
            },
            showlegend: false,
            xaxis: 'x2',
            yaxis: 'y2',
        },
       {
            type: 'scatter',  // all "scatter" attributes: https://plotly.com/javascript/reference/#scatter			
            x: [3000, 4500, 6300, 6500, 3000],     // more about "x": #scatter-x
            y: [0, 1, 1, 0, 0],     // #scatter-y
            marker: {         // marker is an object, valid marker keys: #scatter-marker
                color: 'green' // more about "marker.color": #scatter-marker-color
            },
            showlegend: false,
            xaxis: 'x2',
            yaxis: 'y2',
	    fill: 'tozerox',
        },
	{   x: [1882.34, 4500],
            y: [0.5, 1],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'blue'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [3438.31, 6300],
            y: [0.5, 1],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'blue'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [3438.31, 4500],
            y: [0.5, 1],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'orange'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [4994.28, 6300],
            y: [0.5, 1],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'orange'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [4994.28, 4500],
            y: [0.5, 1],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'red'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [6550.26, 6300],
            y: [0.5, 1],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'red'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [6550.26, 4500],
            y: [0.5, 1],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'magenta'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [8106.23, 6300],
            y: [0.5, 1],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'magenta'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [8106.23, 4500],
            y: [0.5, 1],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'grey'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
	{   x: [9662.20, 6300],
            y: [0.5, 1],
            type: 'scatter',
            mode: 'lines',
	    opacity: 0.35, 
            marker: {color: 'grey'},
            showlegend: false,
	    line: {dash: "dot"},
    	    xaxis: 'x2',
	    yaxis: 'y2',
			},
		very_small,
		very_small_interval,
		small,
		small_interval,
		medium,
		medium_interval,
		large,
		large_interval,
		very_large,
		very_large_interval]);
    }
})
